### ISSUE TITLE
Missing generated prop documentation for TextInput

### ISSUE THREAD

**Issue by colebemis** [primer/react#1419]
## Problem

The `Props` component that we use to generate prop documentation doesn't work with the `TextInput` component:

![CleanShot 2021-09-09 at 15 46 30](https://user-images.githubusercontent.com/4608155/132772395-d550a9d5-c8ff-4143-8ca1-d1333ed86b8b.png)

## Tasks

- [ ] Investigate and fix missing generated prop documentation for `TextInput`

## Notes

The `Props` component was added in [this PR](https://github.com/primer/react/pull/1323) and is implemented with `react-docgen-typescript`. I'm guessing there are other components that don't work with the `Props` component as well.

**Comment by siddharthkp** [comment]
🕵️ This is what I have till now: 

The props don't show up because they aren't generated by `react-docgen-typescript`. It skips the `TextInput` component without a warning. 

They did have trouble with `React.forwardRef` but those [were fixed](https://github.com/styleguidist/react-docgen-typescript/issues/254) in the version we are using. So now, I'm trying to figure out what part of our syntax does docgen not like based on the [test fixtures](https://github.com/styleguidist/react-docgen-typescript/tree/master/src/__tests__/data) in their repo

**Comment by colebemis** [comment]
Excellent detective work, @siddharthkp 🕵️ ✨ 

Seems like the solution to this issue is either simplify the way we right types or change how we generate prop documentation (maybe we could use `ts-morph`). Either way, this seems like more work than we initially estimated. Let's move this back into the backlog until we can prioritize this. 

I also think this calls for a more general discussion about how we want to handle prop documentation (i.e. can it be generated or is manually maintaining it okay?). Can you create a discussion about that in [github/primer](https://github.com/github/primer) or [primer/react](https://github.com/primer/react) when you have a chance?

**Comment by siddharthkp** [comment]
Started a discussion to log exploration work: https://github.com/primer/react/discussions/1492

**Comment by pksjce** [comment]
This doesn't seem to be relevant anymore as TextInput and doc issues have been fixed. Please re-open if required.
