### ISSUE TITLE
The PointerBox is being drawn incorrectly in all dark themes.

### ISSUE THREAD

**Issue by Matosov** [primer/react#1542]
Pay attention for the line near the caret.
<img width="536" alt="Screenshot 2021-10-26 at 13 42 00" src="https://user-images.githubusercontent.com/22476212/138863339-5e566bba-4e4d-42fc-b4f2-3e171de656e1.png">

**Comment by lukasoppermann** [comment]
Hey, so this issue as well as a somewhat related issue of the flash banner in dark mode will be solved with the new token release (primitives-v8). But we don't know when we release it yet.

The issue exists because in dark mode role colors use transparency.

A temp solution would be to add two background colors (using css gradient is probably the best solution here):
- bottom layer bg = `canvas.default` of the mode
- layer above = current role color e.g. `success.subtle`

This will create a non-transparent version.

**Comment by Matosov** [comment]
> A temp solution would be to add two background colors (using css gradient is probably the best solution here):
> 
>     * bottom layer bg = `canvas.default` of the mode
> 
>     * layer above = current role color e.g. `success.subtle`
> 
> 
> This will create a non-transparent version.

Hello!
Thanks a lot for Your hint!
