### ISSUE TITLE
Release SelectPanel accessibility improvements as a draft component

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#2342]
SelectPanel introduced [breaking behavioural changes](https://github.com/primer/react/commit/ace38afb0f469f93fbfea0df488e688005609a62) in [v35.8.0](https://github.com/primer/react/releases/tag/v35.8.0) and that caused issues for consumers. So [we decided to rollback these changes](https://docs.google.com/document/d/1XROq7mBumWcKlSg1_Acj3FXZrhDN1oD4ekL3xv7Hrlw/edit?disco=AAAAaiG_0gY) (see [the PR](https://github.com/primer/react/pull/2338) for ref) and release SelectPanel accessibility improvements as a draft component. 

cc @siddharthkp @hectahertz @bolonio

**Comment by bolonio** [comment]
What were the breaking changes? I remember @hectahertz making the prop `title` optional to avoid breaking changes.

**Comment by broccolinisoup** [comment]
Hi @bolonio 👋🏼 it was more like a breaking **behavioural**  changes as in introducing save and cancel buttons yet we received some feedback from memex team regarding some issues around it. Please see [this issue](https://github.com/github/memex/issues/11943) for more.

This is why we decided to move the SelectPanel changes to a draft component and by doing that, we wouldn't be blocking our consumers while we are addressing the reported issues. Please let us know if you still have any concerns. 🙏🏼

**Comment by siddharthkp** [comment]
Hi!

> What is the process for addressing breaking behavioral changes that were introduced to be accessible? 

To make sure folks we don't block folks from getting fixes and features in new releases, the process is to clone that component and import it from a different path, and keep both in the library in a non breaking way:

```jsx
// current component used on production:
import { SelectPanel } from '@primer/react'

// new accessible  component meant to replace current component:
import { SelectPanel } from '@primer/react/drafts'
```

> We don't want to default to a less-accessible experience.

That's the bug/feature with this approach. Each instance of the current SelectPanel can be moved to the new SelectPanel one at a time, making sure it works and is accessible, while also keep up to date with other updates.

Unfortunately, for a some time, new instances of SelectPanel might accidentally be built on the old one, because that's the default. We solve this by adding a note on the docs to use the new version from drafts, but folks don't always look at the docs before creating a component.

In the next major version, we "promote" the new accessible Select panel to be the default, while still keeping the old version for teams that have not invested the time to upgrade.


```jsx
// accessible SelectPanel, now the default
import { SelectPanel } from '@primer/react'

// old component still available under deprecated
import { SelectPanel } from '@primer/react/deprecated'
```

**Comment by inkblotty** [comment]
Thank you @siddharthkp ! I appreciate the clear process here.

When it comes to evaluating the feature changes that are causing the "draft" state, what is the process?

**Comment by bolonio** [comment]
Hi everyone, I would like to give some context here about those "breaking behavioral changes that we introduced to the SelectPanel to be accessible".

We, @hectahertz and I, did the [Primer React SelectPanel - A11y engineering review](https://github.com/github/primer/issues/1021) with the help of our accessibility consultant @jscholes, and there are a couple of things related with those "behavioral changes" I would like to clarify.

> Before these changes, SelectPanel would call onSelectedChange every time the user would select or deselect an item.
> 
> The UX will change with the recommended layout, as there is a pair of Save and Cancel buttons. SelectPanel should call onSelectedChange only after the user performs a save, and discard the modifications altogether if the user cancels or closes the SelectPanel.
> We strongly discourage the addition of more granular callbacks, so we can keep the control of the pre-saving state local to the component. This approach also keeps the API virtually the same, so upgrades to the new version should be mostly straightforward.

- Source: https://github.com/github/primer/issues/1021

The elements of the list within the SelectPanel act like checkboxes, both for single and multi selection. Checkboxes don't perform actions when checked, they just keep the selection until the save button is clicked.

Someone said in [this comment in the memex / primer weekly sync](https://docs.google.com/document/d/15Wg_CgKH4xTGul6ZfjdxGis_rkWyk2P-brRvUKaPtog/edit?disco=AAAAd3G4Bjk), `"this will change how users have to use this selector only in Memex (currently), which will be a frustrating user experience."`.

We are aware that there are several places in dotcom where we have behaviours that we don't recommend, even if they could be frustrating for non-disabled users, but the component/feature/functionality would not be accessible.

I'm not against "promoting" the new accessible Select panel to be the default, while still keeping the old version for teams that have not invested the time to upgrade. But at the very end, every team will have to implement accessible components to have an accessible platform, and that would request some behavioral changes, since some of the current ones don't match with some of the principles of web accessibility.

As usual, we are always open for discussion, feel free to contact us in slack in [#accessibility](https://github.slack.com/archives/C0FSWLQ0Y) or attend our Accessibility Office Hours. We recommend you to book a slot in the session you're attending. [You can do that searching for that day's session using this search link](https://github.com/github/accessibility/issues?q=is%3Aopen+%5BMeeting%5D+Office+Hours) and adding yourself.

**Comment by broccolinisoup** [comment]
Hi everyone,
Sorry my wording on the ticket description was misleading.
The main reason we need to revert the SelectPanel changes is due to our promise not introducing any breaking changes in the minor releases. (Also following [Semver](https://semver.org/#summary)) However, mistakenly, we released SelectPanel changes with a minor release so we need to take this back to unblock folks and follow Semver standards. The rest is as Sid mentioned, we will release the SelectPanel with all the improvements in the next major release. Please see our list for the [next major v36.x ](https://github.com/github/primer/issues/1294)

Thank you for your understanding 🙏🏼 And as always, please let us know if you have any concerns.

**Comment by inkblotty** [comment]
@broccolinisoup - This makes total sense. Thank you for clarifying, and let us know if you need the Accessibility Team to support.

**Comment by broccolinisoup** [comment]
Thank you!! @inkblotty

**Comment by bolonio** [comment]
Thanks @broccolinisoup for the explanation :) As @inkblotty said and repeating myself:

> As usual, we are always open for discussion, feel free to contact us in slack in [#accessibility](https://github.slack.com/archives/C0FSWLQ0Y) or attend our Accessibility Office Hours. We recommend you to book a slot in the session you're attending. [You can do that searching for that day's session using this search link](https://github.com/github/accessibility/issues?q=is%3Aopen+%5BMeeting%5D+Office+Hours) and adding yourself.

**Comment by lesliecdubs** [comment]
Thanks everyone. Pinging @hectahertz here as a reminder when he's back from being out so we can chat about where this should sit in the priority queue.

**Comment by bolonio** [comment]
I'll leave here a link to a related discussion in the following issue:

- https://github.com/primer/react/issues/2281

**Comment by broccolinisoup** [comment]
Keeping this issue open until we release the remediations in [the next major release](https://github.com/github/primer/issues/1294)

**Comment by broccolinisoup** [comment]
@siddharthkp is this issue still relevant to the select panel work or not so much anymore?
