### ISSUE TITLE
[PageLayout] The `Content` component scrolls in `sticky` stituations

### ISSUE THREAD

**Issue by joshblack** [primer/react#2385]
### Description

The `PageLayout.Content` component seems to have its content scrolled when there is a sticky header or sticky pane present. 

### Steps to reproduce

You can see this issue on both the Sticky Pane and Custom Sticky Header stories:

- https://primer.style/react/storybook/?path=/story/layout-pagelayout--sticky-pane
- https://primer.style/react/storybook/iframe.html?args=&id=layout-pagelayout--custom-sticky-header&viewMode=story

Specifically, when loaded the content is initially scrolled:

![image](https://user-images.githubusercontent.com/3901764/193125554-3524f3fd-2c8e-4272-8bce-b84835ecd115.png)

### Version

v35.10.0

**Comment by MihirGH** [comment]
Hi! Can I take a look at this bug?
Would like to land some contributions as part of Hacktoberfest 22

**Comment by MihirGH** [comment]
@joshblack actually the scroll that you are seeing is because of the custom interaction that runs on these two particular stories of sticky pane and sticky header. If you comment out `CustomStickyHeader.play` and `StickyPane.play` inside `src/PageLayout/interaction.stories.tsx` then the automatic scroll won't happen in these two stories.

**Comment by joshblack** [comment]
Ah perfect, thanks @MihirGH! That's totally it. I'll close this issue out since it's intended from the play functions. Thanks again!
