### ISSUE TITLE
ActionMenu does not have hover styles in Dark high contrast theme

### ISSUE THREAD

**Issue by siddharthkp** [primer/react#2479]
### Description

https://user-images.githubusercontent.com/1863771/197777432-8afc5d79-a5ad-43b8-a3ec-00f92897e5b3.mov

### Steps to reproduce

1. Go to https://primer.style/react/ActionMenu
2. Change theme to Dark high contrast
3. Hover on menu items

### Version

v35.12.0

### Browser

Chrome

**Comment by tallys** [comment]
@siddharthkp let's prioritize a fix for a11y sake

**Comment by lesliecdubs** [comment]
Hi @factscub, this one is already assigned to a Primer React maintainer but if you'd like to give it a go, feel free to submit a PR for consideration.

**Comment by electron97** [comment]
Hey @joshblack, @tallys, @siddharthkp,

I started looking into this issue as it was open for some time now. Below are the following details.

Currently the background of the ActionMenu is set to [${get('colors.canvas.overlay')}](https://github.com/primer/react/blob/main/src/Overlay/Overlay.tsx#L58) which is equivalent to [overlay: get('scale.gray.8')](https://github.com/primer/primitives/blob/main/data/colors/vars/global_dark.ts#L12). Here the overlay value is set to `scale.gray.8` now if we see the hover background of [ActionListItem](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_high_contrast.ts#L208) which is all the elements in the ActionMenu we can see it has a background of `scale.gray.8` as well.  So since both has the same background the ActionMenu doesn't have hover styles. So to fix this we can do few things.

1. We can change the hoverBg of `ActionListItem` over [here](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_high_contrast.ts#L208) from `scale.gray.8` to `scale.gray.6`. But doing this it can change the default hover style behaviour of the ActionListItem and also this change isn't required where the component containing ActionListItem doesn't have a background of `scale.gray.8`.

2. We can add a new variant over [here](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_high_contrast.ts#L204) along with `default` and `danger` which can be named as `actionMenu` and then we can add something like .

```
actionMenu: {
   // this can be change to any other value but keeping it different here from bg which is scale.gray.8 
   // so that hover works
    hoverBg: get('scale.gray.4'),
    activeBg: get('scale.gray.6'),
}
``` 

Since activeBg is also dependent on variant [here](https://github.com/primer/react/blob/main/src/ActionList/Item.tsx#L122) we need to add that as well. All the available `dark_high_contrast` scale gray colors can be found [here](https://primer.style/primitives/storybook/?path=/story/color-base-scales--gray&globals=theme:dark_high_contrast).

And then we can add this new variant in [ActionMenu.stories](https://github.com/primer/react/blob/main/src/ActionMenu/ActionMenu.stories.tsx#L17), [ActionMenu.examples](https://github.com/primer/react/blob/main/src/ActionMenu/ActionMenu.examples.stories.tsx#L135), [ActionMenuStories.featues](https://github.com/primer/react/blob/main/src/ActionMenu/ActionMenu.features.stories.tsx#L14) and this way we can fixed the hover of `ActionMenu` component without affecting any other component which uses `ActionListItem`.


Please let me know what you guys think about this or if you guys have any better suggestions to handle this will be really great.

Thanks!

**Comment by broccolinisoup** [comment]
Hi @electron97 👋🏻 

Thanks so much for taking a look at this issue and digging deep into it! We appreciate your work 🙏🏻 

I humbly have a couple of thoughts regarding the solutions and we can chat further about it them find the best way. 

>We can change the hoverBg of ActionListItem over [here](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_high_contrast.ts#L208) from scale.gray.8 to scale.gray.6. But doing this it can change the default hover style behaviour of the ActionListItem and also this change isn't required where the component containing ActionListItem doesn't have a background of scale.gray.8.

I agree with you. `ActionListItem` is used in multiple places without the `ActionMenu` context and changing it to `scale.gray.6` would change all the other hover backgrounds too. This wouldn't be an isolated change and refraining from this sounds like a good idea 👍🏻 

>We can add a new variant over [here](https://github.com/primer/primitives/blob/main/data/colors/themes/dark_high_contrast.ts#L204) along with default and danger which can be named as actionMenu and then we can add something like .

I would be hesitant about introducing a new variant and updating the variant of `ActionList.Item` components that are used in `ActionMenu` context to the new variant mainly because this would be a breaking chance. And this would require an update in all downstream repos. 

One isolated solution I thought is that maybe we can look into conditionally setting the hover background color depending on where the `ActionList.Item` is used and we might determine this in the code [like we did for roles](https://github.com/primer/react/blob/main/src/ActionList/Item.tsx#L64).  It is inspired by your second solution, it just adds a pivot into it to gather the context in the code rather than explicitly setting with a variant. 

Let me know what you think and if you have any questions or anything I misunderstood! Thanks so much again!

**Comment by pksjce** [comment]
Hi, After some more digging into the issue, I asked @langermank for some advise on whether we should update a primitive for it. She pointed me to `view_component`'s implementation which includes a hover border which shows up in case of this particular theme. 
Here's the [link](https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/alpha/action_menu/default?_display=%257B%2522theme%2522%253A%2522dark_high_contrast%2522%252C%2522primitives%2522%253A%2522default%2522%257D).

With this as a reference, I have a PR correcting this for `primer-react`. However storybook examples for `ActionMenu` in `primitives` also suffer from the same issue. Do we need to fix it as part of this issue? Maybe not?
