### ISSUE TITLE
Button prop disabled does not work with prop as

### ISSUE THREAD

**Issue by ArthurClemens** [primer/react#2633]
### Description

Using `disabled` and `as` does not result in an disabled button:
```
<Button as="a" href="/" disabled>Disabled button</Button>
```

### Steps to reproduce

This can be see in the [Button Link Storybook](https://primer.style/react/storybook/?path=/story/components-button--link-button&args=disabled:true)

### Version

v35.12.0

### Browser

Chrome

**Comment by ericwbailey** [comment]
Hi @ArthurClemens, thanks for submitting this issue. 

The `disabled` attribute is not a valid declaration on the anchor element, nor is it an expected interaction for many assistive technology users. I'll mention the link you provided to the Primer team.

**Comment by mattcosta7** [comment]
I feel like we've had a request for this previously, and it is unexpected that it doesn't work (conceptually), but the fact that `a` tags can't be disabled is important here. 

I think we discussed previously that maybe we should become a disabled `button` element when disabled is present, and only an anchor when not present for these cases?  but the number of places to account for this is difficult (since as can be very broad, when about a deeply nested component that finally renders an a - can we guard there too? I doubt it)

**Comment by ArthurClemens** [comment]
There is a possibility, as described in [Disabling a link](https://www.scottohara.me/blog/2021/05/28/disabled-links.html):

```html
<a role="link" aria-disabled="true">Disabled link</a>
```
This could be styled with:

```css
a[aria-disabled="true"] {
  pointer-events: none;
  color: #ccc; /* some muted color */
}
```

**Comment by ericwbailey** [comment]
A muted color will likely run afoul of [WCAG Success Criterion 1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html). If contrast is brought to an acceptable level, there is also the likelihood of it being visually interpreted as a non-disabled link.

I'm familiar with the article you linked to, and would like to re-emphasize this part from the intro:

>Now, setting aside whether or not disabling a link is even a good idea (opinion: it’s probably not)

This seems like a case of "just because you can doesn't mean you should."

I'd encourage you to revisit the design for an alternate approach instead.
