### ISSUE TITLE
`UnderlineNav2` Flickering problem when moving pages (with nextjs)

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [primer/react#2676]
### Description

I found a new issue flickering UI about UnderlineNav2 while trying to reproduce issue #2651.

https://user-images.githubusercontent.com/15520015/206831112-5536736c-0119-43e2-b6ee-2a1a39c26d77.mov

### Steps to reproduce

1. Go to ~https://codesandbox.io/p/sandbox/primer-underline-nav2-bug-ojlgdh~ https://stackblitz.com/edit/primer-undelinenav2-issue-2651-2676
2. Adjust the width of the preview window until the more button appears.
3. While switching pages, check the flickering on the right side of the nav bar.

### Version

v35.15.1

### Browser

Chrome

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Codesandbox was unstable, so I recreated it with stackblitz.

https://stackblitz.com/edit/primer-undelinenav2-issue-2651-2676

**Comment by joshblack** [comment]
Hi there! 👋 

I believe this happens when components like `UnderlineNav` are expected to share state between route transitions. Because the routes are separate components, there is a flash as the component is mounted and then has to sync with the current state of the world.

This can be solved by moving the shared layout up into `_app.js` or alternatively by using per page layouts (link in: https://nextjs.org/docs/basic-features/layouts#per-page-layouts) in order to preserve state and keep the component mounted between transitions. Here's a quick example with the per-page layout approach: https://stackblitz.com/edit/primer-undelinenav2-issue-2651-2676-qkweh9

Hope this makes sense, let me know if you have any questions or if I misunderstood anything!

**Comment by lesliecdubs** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs I'm going to close this issue as guidance has been provided, but please comment back here if needed and we can reopen the issue. Thanks!
