### ISSUE TITLE
Button programmatic focus doesn't show focus ring

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#2711]
### Description

When moving focus programmatically to a button, focus ring is not enabled, which makes it hard to know where initial focus is.

I think it makes sense to add the focus ring in these cases, since sighted users have no indication of where focus is at this point?

### Steps to reproduce

call `element.focus()` where the element is a button, notice no focus ring

### Version

latest

**Comment by langermank** [comment]
Since we use `:focus-visible` for styling, are you able to target that instead? I remember reading that this is now part of the spec but I can't find a ton of information on it.

https://webplatform.news/#1660387734000

**Comment by mattcosta7** [comment]
@langermank oh, I wasn't aware of that proerty on `.focus()` calls

Looks like it's only experimental in firefox currently.  do we polyfill it in dotcom or primer - if so that could work!

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#browser_compatibility

**Comment by langermank** [comment]
I don't think we polyfill in dotcom. We offer a global `.focus` class which pulls from the same styling as `focus-visible`, but we don't have support for `.focus` on Button styles. For example, the primary Button has a specific style for focus.

**Comment by TylerJDev** [comment]
Hey @mattcosta7!

I took a peek at the example of where this issue stemmed, and gathered some extra context.
It doesn't seem like this is an issue of Primer, but something that's to be expected when using `:focus-visible`.

There's a set of rules that determine what exactly gets the `:focus-visible` styles. A button _shouldn't_ get the `:focus-visible` styles [**if** the previously focused element did not indicate focus](https://www.w3.org/TR/selectors-4/#example-5e32edd8). So if I were to click a button with my mouse and then focus is programmatically set (via `.focus`) when clicked, onto another button that lives in that page, then the `:focus-visible` style would not get applied, which is expected. 

Whereas, if I trigger a button via the keyboard (i.e. `Enter`), `:focus-visible` styles should be applied to the button, as this implies keyboard focus. This is because you triggered the initial button with a keyboard and the previously focused element would be the button which initiated the focus event.

As the implementation stands now, it doesn't seem like an issue, rather something that is expected. All in all, the focus styles will be applied when navigating with the keyboard, even if focus is set programatically.

Please let me know if you have any questions!

**Comment by mattcosta7** [comment]
yep, makes sense.  i'll close given the context!
