### ISSUE TITLE
Resizable SplitPageLayout can grow in size as the screen shrinks

### ISSUE THREAD

**Issue by jdrush89** [primer/react#3219]
### Description

It seems like at a certain breakpoint, the css on the SplitPageLayout.Pane changes and it's width is increased. This shouldn't happen when shrinking the screen, the pane should shrink and the main content should be prioritized.

### Steps to reproduce

1. Launch storybook.
2. Go to the SplitPageLayout story and toggle the pane to be resizable.
3. Resize the pane to be larger.
4. Shrink the window size slowly.
5. Notice that the pane shrinks until it hits 1520px, then it grows

https://user-images.githubusercontent.com/955442/234071194-9e4b4814-c812-4d05-9a50-77c981338814.mov

### Version

v35.25.1

### Browser

Chrome

**Comment by colebemis** [comment]
I dug into this behavior a bit today. It looks like what's happening is the effective "min width" of the content changes from 959px to 511px as you shrink the viewport. When that switch happens, the pane expands to fill the space. I'd love to get some design input on what the expected behavior should be here. I'm going to move this back to the inbox so we can discuss in the next maintainer sync.

**Comment by langermank** [comment]
@colebemis I believe that if a user resizes the pane, that size should remain the same even if the viewport changes _until_ it hits a responsive breakpoint that would control visibility (like if it then stacks, the width would be full).

**Comment by colebemis** [comment]
@jdrush89 Are there any places in the GitHub UI where this behavior is causing issues? Seeing a real-world example would help us decide on what the correct behavior should be and what the priority of this issue is.

**Comment by jdrush89** [comment]
@colebemis yes, you can see it on the codeview if you expand the tree on a wide screen, then shrink the window size.
Here's a repro on https://github.com/github/github/tree/master/.devcontainer

**Comment by jdrush89** [comment]
I don't know what is wrong with issues, but I still can't attach videos. Zach has one on slack if that's helpful.
https://github-grid.enterprise.slack.com/files/UM038LRNF/F05BYRDLM08/funny-tree-view-panel.mov

**Comment by jdrush89** [comment]
Finally got it
https://github.com/primer/react/assets/955442/33b7cb9b-8a7d-4914-ae11-ddd5de5de137

**Comment by colebemis** [comment]
Ah, I see. Thanks for the video @jdrush89. @langermank and I did some investigation into this issue and it's trickier than we expected to fix it. I spoke with @lesliecdubs and we both agree that this is a low priority bug since not many people resize their browser windows.

If your main concern is that the min width of the main content is too narrow at small viewports, that can be adjusted here: https://github.com/primer/react/blob/58b118f2f9475b1afb32cf537ee874786cd23e55/src/PageLayout/PageLayout.tsx#L746
