### ISSUE TITLE
Help: How does the Theming system works?

### ISSUE THREAD

**Issue by alexis-opolka** [primer/react#3573]
### Description

Hi 👋🏼 ,

I am trying to learn how to use this library and I am stuck with an issue regarding the theming system.  
I added `ThemeProvider` and `BaseStyles` components at the root of my `App` component (see [this file](https://github.com/alexis-opolka/alexis-opolka.github.io/blob/theme-system-github-primer/src/app/_app.tsx)) and added in the header a Button to toggle the theme between light and dark themes (see [this file]()), more specifically [this function](https://github.com/alexis-opolka/alexis-opolka.github.io/blob/61b8a3dcb69b9d4b7a7cc37eb6357a3f21115253/src/app/page.tsx#L66-L84) and the way it's called via this [Button](https://github.com/alexis-opolka/alexis-opolka.github.io/blob/61b8a3dcb69b9d4b7a7cc37eb6357a3f21115253/src/app/page.tsx#L87C3-L92).

I don't see where the problem may lie and would highly appreciate any help to solve this issue.  
Thanks a lot in advance. ^-^

### Steps to reproduce

1. Install `@primer/react` as a dependency of a NextJS project.
1. Add `ThemeProvider` and `BaseStyles` to the root of the App component.
1. Create a button (using the `Button` component) to toggle the theme between a light and a dark scheme (from the default schemes).
1. Nothing seems to happen visually, at least.

### Version

v35.26.1

### Browser

Firefox

**Comment by joshblack** [comment]
Hi there @alexis-opolka! 👋 Thanks for taking the time to make this issue 🙏 

When looking at the project that you shared, it seems like `ThemeProvider` and `BaseStyles` may not be loaded in the project since they are in `src/app/_app.tsx` instead of a layout file for the app router. I believe you're usage of the `useTheme` hook is correct, but you'll need to move `ThemeProvider` or `BaseStyles` in to a common layout like `page.tsx`.

Unfortunately, components like `ThemeProvider` don't work in places like `layout.tsx` currently due to `useEffect` 😞 It may be best to continue using the pages router until Primer React is updated to work better in Next.js App Router / React Server Components.

Hope this helps! Let me know if you have any questions or if I misunderstood anything 👀

**Comment by alexis-opolka** [comment]
HI @joshblack 👋🏼 Thanks for your answer! ^-^

It was indeed because I used the `_app.tsx` file instead of `layout.tsx` (I was kinda dumb to not notice it, sorry).
I didn't know the version of NextJS I'm using wasn't loading `_app.tsx` but `layout.tsx`.

I did put both `ThemeProvider` and `BaseStyles` in `layout.tsx` and made it work with the use of the `use client` directive at the top of both `layout.tsx` and `page.tsx` (and any other page importing `layout.tsx`).
It can be a workaround until Primer React is updated. ^-^

Once again, thanks so much. 😄

**Comment by tallys** [comment]
@alexis-opolka thanks for opening this issue, and thanks for the reply @joshblack - is your issue resolved?

**Comment by alexis-opolka** [comment]
@tallys Yes it's now resolved! ^-^

Thanks again for the help! ✨

**Comment by joshblack** [comment]
@alexis-opolka yay! I'm so glad that worked. Thanks so much for the note about `'use client'`, that sounds like a great workaround until we add that into the package itself 👀 

Looks like everything is good to go so I can close this one out! Feel free to comment if I misunderstood anything and we can re-open as-needed 👀
