### ISSUE TITLE
Add Optional target prop to Link component

### ISSUE THREAD

**Issue by alexis-opolka** [primer/react#3640]
Hi 👋🏼 ,
It's me again. ^-^

I'm in a situation where I want to redirect the user to another page in another tab.
To do so, It would mean to set `target='_blank'` in the rendered styled `a` tag.

So, I propose to either add an optional `target` prop (containing a `string` value) to the `Link` component and send it in the underlying styled `a` tag:

```jsx
<Link target="_blank" href="https://example.com"> Some link opening in the same tab / window </Link>
```

Or use a boolean prop to switch between `_self` and `_blank`:

```jsx
<Link newTab={true} href="https://example.com"> Some link opening in a new tab / window </Link>
```

with a logic in the component like:

```tsx
newTab ? '_blank' : '_self'
```

What do you think?

**Comment by lesliecdubs** [comment]
Hi 👋🏻 Thanks for the suggestion!

We have purposely chosen not to expose the ability to open links in another tab in the Primer `Link` component because this behavior can lead to a disruptive and often inaccessible experience. We have been advised that it's preferable to allow the user to make the decision of how they want links to behave, as such we avoid encoding `target="_blank"` and other similar techniques for opening links a new browser tab/window.

I'm going to close this issue for now, but feel free to write back.

**Comment by alexis-opolka** [comment]
Hi,
Oh ok, that makes sense. 🤔
Thank you. ^-^
