### ISSUE TITLE
Unable to reference theme context with sx prop

### ISSUE THREAD

**Issue by robaish** [primer/react#3687]
### Description

Hi!

According to the [documentation](https://primer.style/react/theming#referencing-theme-values), we should use the theme from the same context as Primer and not import an instance of the theme.

I find that I'm able to reference things color, for example: `sx={{bg: 'canvas.default'}}`

But I'm unable to reference for example the `radii` key, so I have to import the theme:
`sx={{ borderRadius: theme.radii[2] }}`

This is against the documentation but seems to work. I wonder if this is by design or a bug?

### Steps to reproduce

1. Use a Primer component
2. Style the border-radius with the sx prop and try to access the radii key without importing an instance of the theme

### Version

v35.26.1

### Browser

Chrome

**Comment by robaish** [comment]
Update, this seems to work:

`sx={{ borderRadius: themeGet('radii.2') }}`

Is this a correct pattern to use? `themeGet` is documented to work in styled components, but seems to work in the sx prop too!

**Comment by siddharthkp** [comment]
Hi! 

> I find that I'm able to reference things color, for example: sx={{bg: 'canvas.default'}}

This works because css properties have a map to the related theme value. So, properties like bg, backgroundColor, borderColor map to `theme.colors`. 

`"canvas.default"` acts like an alias to `theme.colors.canvas.default`, but only when used with a color property!

> But I'm unable to reference for example the radii key, so I have to import the theme:
sx={{ borderRadius: theme.radii[2] }}


`sx={{ borderRadius: 2 }}` should work, `2` would act as an alias to `theme.radii.2`. Or as you figured out `themeGet('radii.2')` would get you to the same alias as well :)

**Comment by siddharthkp** [comment]
Hope that answers your question, feel free to reply back if it doesn't! Or if you have another question :)
