### ISSUE TITLE
TextInput action hover state is incorrect 

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#3867]
### Description

The hover state for clearing an input should just slightly change the icon color instead of providing a background behind it. 
The background right now is also incorrectly sized making it even more apparent that it's implementation is incorrect.

<img width="282" alt="Screenshot 2023-10-26 at 13 44 1" src="https://github.com/primer/react/assets/980622/fe4b1fed-0539-47ed-a625-a65d0284a420">

Additionally the [example in storybook](https://primer.style/react/storybook/?path=/story/components-textinput-features--with-trailing-action) shows the clear button even though there is no input value. This is incorrect behaviour and could encourage a wrong pattern. It's crucial that the clear button is hidden when the input is empty. Therefore I suggest adding this simple functionality in storybook and be default add a value to it.

### Steps to reproduce

1. Go to https://primer.style/react/storybook/?path=/story/components-textinput-features--with-trailing-action
2. Hover the clear button

### Version

v35.32.1

### Browser

Safari

**Comment by cs25-esc** [comment]
hi !
can you assign this to me?

**Comment by lesliecdubs** [comment]
Sure thing @cs25-esc, sending this your way! For reference, here's a link to the [contribution guidelines](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md). Let us know if run into questions.

**Comment by cs25-esc** [comment]
sure thanks @lesliecdubs

**Comment by cs25-esc** [comment]
Hi @lesliecdubs i could solve the issue "clear button will not be displayed when there is no input" for another issue where can i find the CSS or styling files assosciated with clear button ?

**Comment by cs25-esc** [comment]
Hi @lesliecdubs / @maximedegreve fixed both the issues on my local
i have a doubt like : on hovering the clear input icon you said it should change the icon color slightly (what does it mean, shall i change the opacity of the icon or altogether a different color?)

**Comment by cs25-esc** [comment]
https://github.com/primer/react/assets/68850280/da93f4c7-d8c5-431e-a9c3-7dcee666cfd7

@lesliecdubs / @maximedegreve can you please verify this

**Comment by maximedegreve** [comment]
This looks good @cs25-esc 🎉

**Comment by cs25-esc** [comment]
Hi @maximedegreve / @lesliecdubs i have submitted my PR for this issue.

**Comment by siddharthkp** [comment]
Bringing this issue back to prioritisation because we need to think if there's a way we can bake this into the component itself. 

Some actions like `clear` should only appear when there is content inside the input, but other actions might be visible from the start.

What we can confidently do here is update the example in storybook to a different action like copy that doesn't violate our design guidelines

**Comment by siddharthkp** [comment]
There are 3 parts of this issue:

1. The hover state for clearing an input should just slightly change the icon color instead of providing a background behind it.

   We use an [IconButton with variant=invisible](https://primer.style/react/storybook/?path=/story/components-iconbutton-features--invisible&globals=colorScheme:light) as the action, which comes with it's own hover styles. We can change component styles for trailing action for that. 

   @maximedegreve Should open [another issue for PVC as well](https://primer.style/view-components/lookbook/inspect/primer/alpha/text_field/playground?show_clear_button=true)

2. Our [trailing action example in storybook](https://primer.style/react/storybook/?path=/story/components-textinput-features--with-trailing-action) doesn't match our own design guidelines. 

   > This is incorrect behaviour and could encourage a wrong pattern. It's crucial that the clear button is hidden when the input is empty.

   Because we want to show trailing action in the example, what we can do here is add a default value to the input to show the action and then hide it if you remove the text. To make this story even clearer, we can add two text inputs, one with text and one without.

3. `clear` action should only appear when there is content inside the input, but other actions might be visible from the start.

   This is the tricky part. Right now, it's up to the application to handle that. We should probably bake this behavior into the component for `clear`. [PVC has an attibute called `show_clear_button`](https://primer.style/components/text-input/rails/alpha#:~:text=Primer%27s%20Octicon%20component.-,show_clear_button,-N/A), works but not a big fan. Needs more thought.

**Comment by lesliecdubs** [comment]
@cs25-esc thanks for helping out with this! Would you be willing to replicate the same change to the hover state style in Primer ViewComponents https://github.com/primer/view_components as well?

**Comment by cs25-esc** [comment]
> @cs25-esc thanks for helping out with this! Would you be willing to replicate the same change to the hover state style in Primer ViewComponents https://github.com/primer/view_components as well?

yeah sure let me check.

**Comment by cs25-esc** [comment]
@lesliecdubs I'm thinking like let me wait for the PR - https://github.com/primer/react/pull/3894 to get done before making the same changes for Primer ViewComponents.

**Comment by lesliecdubs** [comment]
That sounds reasonable to me, @cs25-esc! I'm going to leave this issue assigned to you for now; just let us know if you aren't able to come back to it.

**Comment by siddharthkp** [comment]
@maximedegreve How do you feel about the visual feedback here?

The icon color for IconButton is `fg.muted`. For trailing action, I've changed that to `fg.subtle` and then setting it to `fg.muted` on hover, is that enough feedback or is that too subtle (see video below)? 

https://github.com/primer/react/assets/1863771/6b07d8bb-846f-40a0-87a7-c66182a63504

See storybook with all color modes: _loading..._

**Comment by dusave** [comment]
@cs25-esc @lesliecdubs Circling back on this thread, did this get fixed from the Primer side?

**Comment by lesliecdubs** [comment]
@dusave looks like the associated PR that was in progress https://github.com/primer/react/pull/3894 didn't end up getting merged. @siddharthkp would reviving https://github.com/primer/react/pull/3894 for reviews be a big lift?

**Comment by siddharthkp** [comment]
- Revived in https://github.com/primer/react/pull/4831
