### ISSUE TITLE
The Dialog component in the old document can work properly, while the new one cannot.

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4114]
- The `Dialog` component example for using the new document (https://primer.style/components/dialog/react) is not functioning correctly; there is no response after clicking the button, and there are no error or warning outputs either.
- The `Dialog` component example for using the old document (https://primer.style/react/Dialog), works correctly without any issues.
- Version Information:
    - primer/react 36.5.0
    - React 18.2.0
    - sass 1.69.5
    - styled-components 5.3.11
    - typescript 5.2.2
    - vscode 1.85.1 (universal)
    - node 21.3.0
    - vite 5.0.8

**Comment by lesliecdubs** [comment]
Hi @meiyingqishi 👋🏻 Thanks for reaching out. 

Are you able to provide a recreation example of the latest PRC `Dialog` (https://primer.style/components/dialog/react from @primer/react@36.4.0) where there is no response after clicking the dialog button? A [Codespace](https://github.com/features/codespaces), [codesandbox](https://codesandbox.io/), or [codepen](https://codepen.io/) example is fine if you aren't able to share source code directly. Thanks!

**Comment by meiyingqishi** [comment]
Hi @lesliecdubs , thanks for your response.

- The GitHub repository is https://github.com/meiyingqishi/primer-demo
- The Codespaces is https://opulent-rotary-phone-vx7w455gjq3p79r-5173.app.github.dev
- The core key code is https://github.com/meiyingqishi/primer-demo/blob/main/src/App.tsx

**Comment by broccolinisoup** [comment]
Hi @meiyingqishi 👋 Sorry for the late response. I cannot load the codespace but had a look at the code you provided [here](https://github.com/meiyingqishi/primer-demo/blob/main/src/App.tsx), seems like you are not importing the new Dialog from the draft bundle if I understand correctly. 

If you could update the new dialog as

`import {Dialog as DialogV2} from @primer/react/drafts` and update the new Dialog example to be `<DiloagV2`, I think the issue will be resolved 🤞  

Also, sorry for the confusion, we are still refining our docs to reflect the correct usage of the various states (stable, draft, deprecated etc) on our updated documentation site [https://www.primer.style/components](https://www.primer.style/components). The one you are viewing on https://primer.style/components/dialog/react is the Alpha Dialog (aka old Dialog because we are recommending usage of the Draft one.) but the draft components are not viewable on the new documentation site yet (WIP - coming soon). You can access the documentation of the draft dialog on https://primer.style/react/drafts/Dialog.

Let me know if the issue still persist, happy to help further 🙌

**Comment by meiyingqishi** [comment]
Thank you @broccolinisoup , the issue has been resolved. 

However, upon reviewing the documentation again, I noticed that it has been modified. The updated document's sample code works correctly, but the functionality implemented by clicking the button does not match the provided code. 

I suggest rolling back to the previous version of the document (which has a more powerful functionality and effect). Simply change the version identifier in the document from **Alpha** to **Draft**, and update the import statement from `import {Dialog} from '@primer/react'` to `import {Dialog} from '@primer/react/drafts'`. This will eliminate any confusion or misleading information.

**Comment by broccolinisoup** [comment]
Hey @meiyingqishi 👋 

>The updated document's sample code works correctly, but the functionality implemented by clicking the button does not match the provided code.

Yes, unfortunately this is still due to an ongoing documentation improvements. Apologies for the inconvenience. It is still a WIP and hopefully soon we will be able to resolve all misleading issues. In the meantime for Dialog v2, please refer to the https://primer.style/react/drafts/Dialog

I am going to close this issue, I don't think there is anything left to be addressed here but please feel free re-open if I miss anything. Thanks!
