### ISSUE TITLE
TreeView: Add support for external styling

### ISSUE THREAD

**Issue by ayy-bc** [primer/react#4487]
### Description

We are using TreeView in the NestedListView and we needed to override some styling to match the design needs for using NestedListView for SubIssues.

Currently, we are using css selectors to override some of the styles (which seems a little hacky) and thought it would be helpful we could pass styles using a prop.

Example PRs:
- https://github.com/github/github/pull/320799
- https://github.com/github/github/pull/320836

**Comment by siddharthkp** [comment]
Hi! Thanks for taking the time!

> Currently, we are using css selectors to override some of the styles (which seems a little hacky) and thought it would be helpful we could pass styles using a prop.

I see TreeView doesn't support sx for all the child items. This was partially intentional at the time of building it so that the design does not deviate too much. The use cases however are many and varied now (like NestedListView!)

We want to phase out styling through a prop (sx) over time, so I would recommend using classNames. However, TreeView does not have reliable selectors that you can target yet. Would that be a useful change for you?

**Comment by iansan5653** [comment]
@siddharthkp I think a good solution would be to support custom styling on `TreeView` and `TreeView.Item`. That could be via the `sx` prop or `className` prop (or maybe both for this in-between time). 

> However, TreeView does not have reliable selectors that you can target yet. 

I think we should probably avoid getting into the habit of exposing targetable selectors, because it makes things difficult to change. Long term, it will make it harder for PRC to move to CSS Modules because the class names would need to remain static. 

If there's specific things we want to support styling internally, I think we should either add props for the required variants, like `hideNestingIndicators`, or we should add support for more externally defined classnames rather than defining new internal classnames, like `nestingIndicatorClassName`.

Or, one more option might be to set `data-` attributes for selection instead of classes, which preserves encapsulation. But I think we'd want to document those and personally I'd prefer some props-based approach that can be typechecked vs an approach that requires more complex CSS selectors.

**Comment by JelloBagel** [comment]
Closed by https://github.com/primer/react/pull/4512
