### ISSUE TITLE
Dark keybinding indicator when used with emphasis

### ISSUE THREAD

**Issue by alondahari** [primer/react#5351]
### Description

This is a recent regression introduced [in the latest version](https://github.com/primer/react/pull/5252).

We're seeing an issue with how the keybindings indicator on the Button component looks in Issues.

![Image](https://github.com/user-attachments/assets/08399e3d-eaa7-4635-9bef-bf6e82058802)

There is currently no way that we see that we can use keybinding hint component with a primary button.

### Steps to reproduce

1. Add a `KeybindingHint` to a primary button
2. With `onEmphasis`, it has a dark background. With `normal` variant, it has a dark fore colour.

![Image](https://github.com/user-attachments/assets/5b4f49d3-df71-44ba-b0b6-d60dcd707f62)

### Version

v37.6.0

### Browser

Chrome

**Comment by francinelucca** [comment]
Summary:
This is an intended change resulting from https://github.com/primer/react/issues/4759. New designs are in the making and the reporting team will workaround with style overrides for now

**Comment by francinelucca** [comment]
TODO: once a fix for this is released, go back and "revert" workaround

**Comment by RJohnPaul** [comment]
Here is a potential solution that you can consider for the issue [Dark keybinding indicator when used with emphasis](https://github.com/primer/react/issues/5351):

Solution
The issue seems to stem from the CSS styling applied to the KeybindingHint component when used with a primary button. To fix this, you can override the default styles by adding custom styles specifically for the KeybindingHint component when it's used with the primary button. Here is an example of how you can achieve this:

CSS
/* Add this CSS to your stylesheet */
.primary-button .keybinding-hint {
  color: #fff; /* Adjust the color as needed */
  background-color: #005cc5; /* Adjust the background color as needed */
  /* Add any other necessary styles */
}
Steps to Apply the Fix
Locate the stylesheet where you define custom styles for your project.
Add the above CSS rules to the stylesheet.
Ensure that the styles are correctly applied by refreshing the page and checking the KeybindingHint component on the primary button.
Comments
