### ISSUE TITLE
Default Label colors

### ISSUE THREAD

**Issue by emplums** [primer/react#858]
Lets add the suite of default label colors + documentation for when to use them, like Primer CSS does here: https://primer.style/css/components/labels#colored-labels

We'll need to think through the best way of handling this in the component API. We already allow folks to customize font color via the `color` prop and bg color via the `bg` prop to accommodate custom colored labels like those in issues. 

The different color combinations are called `themes` in Primer CSS, but we already use the word `theme` a lot in Primer React Components when talking about themes & the theme provider. Maybe `colorScheme`? 

cc @BinaryMuse for thoughts on any considerations we should take into account for the color mode work as well!

**Comment by colebemis** [comment]
Hmm, I feel like this could be a good use case for the `variant` prop, but we're already using `variant` to control the size. If we were working with from a blank slate, I'd say we should use a `variant` prop to control the color of the label and a `size` prop to control the size. But I know that'll be a breaking change API change 😓

To accommodate update color modes, we probably want to name the variants based on their function (e.g. "success" instead of "green"), as we do in the [`Flash`](https://primer.style/components/Flash) component. 

Also, this issue made me think that we should probably have some prop naming guidelines in our documentation if we don't already.

**Comment by BinaryMuse** [comment]
> and a `size` prop to control the size

Agree about the naming guidelines but in particular we can't use `size` because of a styled-system issue IIRC (we removed all instances of `size` in favor of `variant` in the past)

**Comment by colebemis** [comment]
We will be refactoring the `Label` component as part of the [component API consistency](https://github.com/github/primer/issues/220) work. Closing this in favor of a complete refactor of `Label`
